### ISSUE TITLE
Server wake up worker twice at same time

### ISSUE THREAD

**Issue by mike442144** [gearman/gearmand#12]
I ran into a problem:
worker: CAN_DO
worker: PRE_SLEEP
worker: CAN_DO
worker: PRE_SLEEP // two different functions registered completed
server: NOOP
worker: GRAB_JOB
server: NOOP
worker: GRAB_JOB
server: JOB_ASSIGN
server: JOB_ASSIGN

above is the communication between Server and Worker, in the course of nature, Server would wake up the worker use `NOOP` just once, and waiting Worker to send `GRAB_JOB` request. What is strange is the worker received two Jobs, say `a` and `b`, with different payload content meanwhile the same Job Id(in Gearman server is named Handle like: H:localhost:5113). That is the problem, Server deleted the Job Id after received the first `WORK_COMPLETE` message, then Server cannot get second job since it is deleted. Maybe I can figure out in `gearman_server_job_get` function, but there is no debug information:

```
gearman_server_job_st *gearman_server_job_get(gearman_server_st *server,
                                              const char *job_handle,
                                              const size_t job_handle_length,
                                              gearman_server_con_st *worker_con)
{
  uint32_t key= _server_job_hash(job_handle, job_handle_length);

  for (gearman_server_job_st *server_job= server->job_hash[key % server->hashtable_buckets];
       server_job != NULL; server_job= server_job->next)
  {
    if (server_job->job_handle_key == key and
        strncmp(server_job->job_handle, job_handle, GEARMAND_JOB_HANDLE_SIZE) == 0)
    {
      /* Check to make sure the worker asking for the job still owns the job. */
      if (worker_con != NULL and
          (server_job->worker == NULL or server_job->worker->con != worker_con))
      {
        return NULL;
      }

      return server_job;
    }
  }

  return NULL;
}
```
Server return error message is:
 ````
code=JOB_NOT_FOUND, msg=Job does not exist on server
code=JOB_NOT_FOUND, msg=Job given in work result not found
```

Any idea?

**Comment by SpamapS** [comment]
Hi Mike, thanks for taking the time to report this issue as well. Please include the version of gearmand you're using. In reading the code in git, the handle is generated from a counter per server object and a prefix which defaults to nodename, which defaults to localhost. I wonder if you're using any persistence backends that might have pulled in handles that subsequently never got handled. If so, that would indicate a bug in the persistence restoration code, since it should be advancing the counter to the maximum of handles it reads in +1.

So, to be clear:

- [ ] Need version information
- [ ] Do you use persistence?

**Comment by mike442144** [comment]
I'm using gearmand 1.1.12, and no persistence.

**Comment by mike442144** [comment]
It turns out that the communication between server and worker is exactly correct because the worker send  twice of GRAB_JOB message, the exception must be caused by other mistake so I will close the issue and reopen if any further progress.
