### ISSUE TITLE
How to fix "GEARMAND_WAKEUP_RUN(Bad file descriptor)" error ?

### ISSUE THREAD

**Issue by soooldier** [gearman/gearmand#135]
I had found some errors in my error log:
```
ERROR 2017-08-18 09:46:02.000000 [  main ] GEARMAND_WAKEUP_RUN(Bad file descriptor) -> libgearman-server/gearmand_thread.cc:399
ERROR 2017-08-18 09:56:30.000000 [  proc ] GEARMAND_WAKEUP_RUN(Bad file descriptor) -> libgearman-server/gearmand_thread.cc:399
```
what does it means and how to fix it?

**Comment by SpamapS** [comment]
gearmand uses threads to do various CPU-bound tasks concurrently such as parse and serialize packets. It uses pipes to communicate between them and the main thread. I believe there may be situations where if a connection receives packets while gearmand is shutting down, it might cause this to race where the connection's thread gets a packet and tries to tell alert the main thread, but the main thread has already closed the FD for that one, and is expecting the connection thread to die.

Do you maybe restart gearmand regularly around that time? Otherwise, it's a bit of a mystery.

Also, please include what exact version you're running and on what OS. Thanks!

**Comment by esabol** [comment]
Just out of curiosity, are you using SSL, @soooldier ?

**Comment by BrianAker** [comment]
Could you provide more of the log? Were you shutting anything down?

The “error” may be normal churn that just happens at times. Clients behaving badly is somewhat expected (scripts exit from errors, sysadmins fat finger upgrades, noc monkeys gut check machines, squirrels do swan dives into transformers,... cosmic rays flip bits in processors (at least on Sun hardware)).

More information is needed, though I would look and see if your app has a problem.

**Comment by soooldier** [comment]
@SpamapS @BrianAker  Thank you for your reply. 
```shell
[root@gearman_15_100 ~]# cat /proc/version
Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) )

[root@gearman_15_100 ~]# cat /etc/redhat-release
CentOS release 6.5 (Final)

[root@gearman_15_100 ~]# /usr/local/gearman/bin/gearadmin --server-version
1.1.16
```
besides, i restart gearmand at that time ~

**Comment by soooldier** [comment]
@esabol I didn't use SSL ~ just start gearmand as bellow:
`shell
/usr/local/gearman/sbin/gearmand -j 3 -l /home/ziroom/data/supervisor/gearman.log -P /usr/local/gearman/var/gearmand.pid --http-port 4730 -R -q redis --redis-server xx.xx.xx.xx --redis-port 6408
`

**Comment by SpamapS** [comment]
I didn't fully understand your reply.

Are you saying you _did_ restart `gearmand` around the time of the errors?

**Comment by soooldier** [comment]
@SpamapS Yes, that's right.

**Comment by SpamapS** [comment]
Ok, that explains the errors. They can be safely ignored.

**Comment by soooldier** [comment]
@SpamapS Thanks very much :)
