### ISSUE TITLE
Unable to build RPM on Centos 7

### ISSUE THREAD

**Issue by cetanu** [gearman/gearmand#148]
Is there any known issues with this?

I've cloned this repository and run the following:

    ./bootstrap.sh -a
    ./configure
    make
    make rpm

`make rpm` says there is nothing to do

I tried `make dist-rpm` also, but this fails because the tar produced by `dist` is incorrectly named, it seems to have the name `gearmand-1.1.17-6-<random hex>.tar.gz`.

Also, I had to manually create a rpmbuild folder in the root directory. I'm guessing that this is all expected to be created by the user? If this is the case, the readme needs an update, as it says that we can simply use `make rpm`

**Comment by SpamapS** [comment]
I'm certain this is broken because of the version<->git integration I built when we migrated to github. The tar is correctly named, bbut the dist-rpm command and rpm command likely aren't built to handle this integration.

I'll tag this as a bug. I don't have time to address it, but I'd definitely have time to review patches that fix it. Even better, if you could write a TravisCI test that tests building rpms, that would be fantastic.

**Comment by illuusio** [comment]
Now there should be fix for this which is merged on master

**Comment by esabol** [comment]
Can this issue be closed? It seems to have been resolved, right?

**Comment by cetanu** [comment]
Indeed!
