### ISSUE TITLE
There is no configure file on the master branch

### ISSUE THREAD

**Issue by lockland** [gearman/gearmand#162]

**Comment by esabol** [comment]
There shouldn't be a configure file in the repository. The configure file is generated when a release is made. That's how development typically works.

If you want to compile from source and you just want to ./configure and, then I recommend downloading the latest release tarball (*.tar.gz) here:

https://github.com/gearman/gearmand/releases

If you want to work with the code in the GitHub repository because you are planning to do a pull request or submit some kind of patch, please refer to the Contributing section of  https://github.com/gearman/gearmand/blob/master/README.md.

Regards.

**Comment by lockland** [comment]
Thank you for your reply.
I was my fault because I didn't read the document you mentioned, so I going to close this issue.
