### ISSUE TITLE
Unexpected Worker Timeout (CAN_DO_TIMEOUT) Behavior 

### ISSUE THREAD

**Issue by bmeynell** [gearman/gearmand#196]
### Current Behavior

1. `w` worker registers that it can work `f` function for `t` time.
    - In other words., `w` advertises its ability to `CAN_DO_TIMEOUT` instead of `CAN_DO`.
1. `w` receives `j` job.
1. Time `w` takes to process `j` exceeds `t`.
1.  **`w` does _not_ fail `j`.**
1. **`w` sits _idle_ for _exactly 1000 seconds_.**
1. After 1000 _seconds_, _`w` DOES fail `j`._

### Expected Behavior

1. `w` worker registers that it can work `f` function for `t` time (milliseconds).
    - In other words., `w` advertises its ability to `CAN_DO_TIMEOUT` instead of `CAN_DO`.
1. `w` receives `j` job.
1. Time `w` takes to process `j` exceeds `t`.
1.  **`w` fails `j`.**

### References

- Launchpad [bug report](https://bugs.launchpad.net/gearmand/+bug/1458729).
- `ext-gearman` (PHP binding) [bug report](https://github.com/wcgallego/pecl-gearman/issues/58).
- `CAN_DO`: https://github.com/gearman/gearmand/blob/7d6f7570d48a90cd8947579d1bd3718b2aa8f3e6/PROTOCOL#L318-L325
- `CAN_DO_TIMEOUT`: https://github.com/gearman/gearmand/blob/7d6f7570d48a90cd8947579d1bd3718b2aa8f3e6/PROTOCOL#L327-L335
- 1000 Seconds: https://github.com/gearman/gearmand/blob/7d6f7570d48a90cd8947579d1bd3718b2aa8f3e6/libgearman-server/connection.cc#L690-L693
- Timeout Handling: https://github.com/gearman/gearmand/blob/e2d76cf631414964decc2f22006a666e1c0e2424/libgearman-server/connection.cc#L688-L728
- `CAN_DO_TIMEOUT` as [handled](http://cpansearch.perl.org/src/PALIK/Gearman-Server-v1.140_001/lib/Gearman/Server/Client.pm) by the Perl Server.

> Note: _All timeouts alluded to above have **NOTHING** to do with _**SOCKET TIMEOUTS.**__

**Comment by esabol** [comment]
According to the API, is the timeout supposed to be given in milliseconds or seconds?

If milliseconds, the error is at
https://github.com/gearman/gearmand/blob/7d6f7570d48a90cd8947579d1bd3718b2aa8f3e6/libgearman-server/connection.cc#L720
where the value in milliseconds is improperly converted to a `struct timeval`. Need to do something like this instead:
```C
int milliseconds = worker->timeout
struct timeval timeout_tv;
timeout_tv.tv_sec = milliseconds / 1000;
timeout_tv.tv_usec = (milliseconds % 1000) * 1000;
```

**Comment by esabol** [comment]
Milliseconds makes sense for a connection timeout, but not for a job timeout, IMHO. I would favor seconds.

@p-alik, does Perl Gearman::Worker use seconds?

**Comment by esabol** [comment]
@SpamapS, @p-alik, @BrianAker: Any thoughts on this?

**Comment by bradfitz** [comment]
Given that the timeout is transmitted in ASCII (not as some big endian uint32 or uint64) in the protocol, and because of the original Danga implementation, my vote is to define it as fractional seconds. If you want milliseconds, you can write 100ms as `0.1` on the wire.

**Comment by esabol** [comment]
I note that the following:

* All of the examples appear to indicate that the timeout is in milliseconds, such as this: https://github.com/gearman/gearmand/blob/6d262367a59e0643bc84209f83372e3ce8d27dd3/examples/wc_worker.cc#L71

* Throughout the code, the timeout is inconsistently represented by an integer-ish type, either int32_t or int or long, as in here: 
https://github.com/gearman/gearmand/blob/6d262367a59e0643bc84209f83372e3ce8d27dd3/libgearman-server/server.cc#L546

So it seems like @BrianAker's intention was for the timeout to be in milliseconds?

Changing the timeout to be a double (in order to support decimal seconds, as used by @bradfitz in the Danga server) throughout the code would be a big change to the code, I think. I think the better solution is to parse it as seconds (into a double) and then convert that double value to a long in milliseconds. That would entail fewer changes to the code.

Or we could keep it as milliseconds and just fix the bug in the conversion of milliseconds to struct timeval.

Either way, fixing it is easy, but deciding what to do is difficult.

Anyone want to weigh in? @p-alik ?

**Comment by esabol** [comment]
> Or we could keep it as milliseconds and just fix the bug in the conversion of milliseconds to struct timeval.

Almost a year later(!), I just submitted a PR which assumes the timeout is specified in milliseconds and fixes the conversion of milliseconds to a timeval. It seems the simplest course of action to take to fix this bug.

**Comment by esabol** [comment]
Unless you want to wait until gearmand is released, this issue can be closed.

**Comment by Nibbels** [comment]
We had a working gearman setup with 1.1.18 running.
We use PHP https://github.com/brianlmoon/GearmanManager + /net_gearman
The configuration .ini inherited this line: 

>; Timeout n seconds for all jobs before work is reissued to another worker
>timeout = 300

Then the version was increased to 1.1.19 because the system got patched by an admin. Afterwards most of the workers did still run successfully, but ...

If the work of a worker took longer than 1 second the client did read "work_failed" (14) from the socket.
The worker however continued its work and completed it successfully. But at the time of an successful result, the client was not listening anymore. Each job looked like a fail.

After days of debugging we found this thread.
You did change the "seconds" to milliseconds. So the actual fix was:

>; Timeout n milliseconds for all jobs before work is reissued to another worker
>timeout = 300000

I hope with this response other affecteds will find this thread via google.

**Comment by SpamapS** [comment]
I will take a look at the code later today but if we did that it is a
regression and we need to revert and release a fix. Thanks for reporting,
sorry for the trouble.

**Comment by esabol** [comment]
The units for the timeout value were never documented or specified, so it can't be a regression, @SpamapS. The change was intentional and made after a long discussion period seeking input and was approved by both you and p-alik.

**Comment by SpamapS** [comment]
My memory of the last 2 years is challenged by multiple work/life balance
traumas. I'll take your word for it. Ugh.

**Comment by brianlmoon** [comment]
> The units for the timeout value were _never_ documented, so it can't be a regression, @SpamapS. The closest thing to documentation was an example, and the example program's options indicated milliseconds. The change was intentional and made after a long discussion period seeking input from major stakeholders as to what the units should be, and the pull request was approved by both you and p-alik.

While it should not be a regression, I would have expected a minor point release. Seems like this kind of change should have gone into 1.2.x and not in the 1.1.x release series. It is BC breaking.

**Comment by esabol** [comment]
@brianlmoon: If you read the original issue at the top of this page, timeouts didn't work at all prior to this change. This was a bug fix. Workers *always* waited at least 1000 seconds before timing out because the code that set the timeout was wrong, regardless of whether the value as provided was considered to be seconds or milliseconds. In addition to @bmeynell who reported the issue, I tested it myself, and that's what I saw. If you experienced it actually working, then it was a fluke and not what anyone here has seen. The code was wrong both ways. To fix it properly, a decision had to be made as to whether to interpret the value as seconds or milliseconds. Maybe the minor version number should have been incremented, but that boat sailed two years ago.

P.S. The timeout implementation is very buggy, and I wouldn't recommend using it *at all*. But that's a separate issue....

**Comment by SpamapS** [comment]
Sorry @esabol I had forgotten that whole saga. :) Indeed, I think bumping beyond patch level might have been a good idea given that those numbers were being ignored and had been documented ambiguously, and we made some opinionated decisions about what they meant.

But what's done is done, and changing it now would likely do as much harm as we already did. Sorry for the trouble @Nibbels, and it's good to see you still chugging away with Gearman @brianlmoon!
