### ISSUE TITLE
gearmand works very slow when free RAM runs out

### ISSUE THREAD

**Issue by maxwp** [gearman/gearmand#245]
gearmand version 1.1.18 (latest) works very slow when free RAM runs out. I have 64 GB RAM on server and when gearman use all free memory and goes to 1mb of swap - gearmand starts to work very-very slowly.
Adding any task to background que can take up to 10 seconds. Removing task from que can take up to 30 seconds.
And que filled to 10 000 000 jobs for 6-8 hours.

When I kill some other processes to free memory - gearman will still be in swap and I will need to restart gearman too (and loose all data).

**Comment by SpamapS** [comment]
Yes, this is true of all unix processes on servers with swap configured.

Gearman has always been designed to work in RAM, and to "scale out". So if you want to be able to enqueue more things than those that fit in RAM on one machine, you have two options:

1) Add another gearmand. Clients should all be able to submit to two servers, and if written correctly, will load balance by hashing the unique value for each job. Workers should already also have the ability to listen for jobs on more than one server connection.

2) Write a worker which reads jobs from the queue and writes them to disk storage, and then re-submits them when RAM is available. This should be more efficient than swap, and protects you from losing all of the data. This also has the advantage of scaling out, since you can write *lots* of workers that do this, not just one per server. There are a few examples of this, including [Garivini](https://github.com/dormando/Garivini) and [Gearstore](https://github.com/SpamapS/gearstore).

All in all, I don't think there's anything for the gearman community do do here, so I'm closing the issue. But if you have ideas for what solutions there might be for this other than those above, feel free to re-submit or re-open this issue.

Thanks for your interest in gearman!
