### ISSUE TITLE
Gearman is not working with my php7.2+NGINX+ubuntu

### ISSUE THREAD

**Issue by ziyaindia** [gearman/gearmand#259]
See phpinfo

http://148.251.49.106/info.php

`<?php

/**
 * @version: 5.1
 */

class FNSGearman {
    public $gmclient;
    public $taskCount = 0;

    public static $results = array();
    public static function reset(){
        GearmanResults::$results = array();
    }

    public static function completeCallback($task) {
        $unique = $task->unique();
        if ($unique != null) {
            FNSGearman::$results[$unique] = $task->data();
        }else {
            array_push(FNSGearman::$results, $task->data());
        }
    }

    public function addTask($func_name, $arguments, $context = null, $uid = null) {
        $this->taskCount++;
        $this->gmclient->addTask($func_name, $arguments, $context, $uid);
        //if($_SERVER['REMOTE_ADDR']=='103.93.137.91')die('Test');
        //echo $this->taskCount;print_r($arguments);die('Test - addTask');
        //Below code Commented By Ziya
        if ($this->taskCount == MAX_GEARMAN_TASKS) {
            $this->gmclient->runTasks();
            $this->taskCount = 0;
        }
    }

    public function runTasks() {
        //return true;//Commented By Ziya
        if ($this->taskCount > 0) {
            $this->gmclient->runTasks();
            echo $this->taskCount;die();
        } 
    }

    public function __construct() {
        $this->gmclient= new GearmanClient();
        //var_dump($this->gmclient);die('chala');
        //print gearman_version();die('reached');
        /* add the default server */
        $this->gmclient->addServer('localhost',4730);
        $this->gmclient->setCompleteCallback("FNSGearman::completeCallback");
    }
}

?>
`

**Comment by esabol** [comment]
Sorry, this is the repo for gearmand, not the Gearman PECL PHP interface. We don't maintain the latter here. Please close.

**Comment by ziyaindia** [comment]
Could you please suggest me what is the best for me gearmand or gearman pecl php interface?

**Comment by esabol** [comment]
Sorry, but I do not understand your question.

**Comment by MysteryDragon** [comment]
@ziyaindia `gearmand` is common tool, it's not language specific. You need that anyway. (And you have it.)
But most certainly your problem lies in _adapter for gearmand in PHP_, which is https://github.com/wcgallego/pecl-gearman for PHP 7 (works good for versions up to 7.3 _at this moment_). You need them too (and seems that you have one), but perhaps it's better to upgrade it's version. All information can be found at https://github.com/wcgallego/pecl-gearman/blob/master/README, or if your adapter is intalled via package manager, it's even better (just update that package in this case).

**Comment by esabol** [comment]
Please close this issue.
