### ISSUE TITLE
No way for client to see if there are any registered workers for function

### ISSUE THREAD

**Issue by jordancox1234** [gearman/gearmand#314]
I need a client to see if there are any workers for a function before it submits the job to the server.

**Comment by esabol** [comment]
`status` does this, doesn’t it? Have you looked at that?

**Comment by SpamapS** [comment]
status is something that will work for this, but it's not to be done
lightly.. in order to enumerate and count the hash tables, gearmand must
lock them. We could definitely make it more scalable, but by and large,
it's not something you want *all* of your clients doing. Also if you have
multiple gearmand's, you're going to need to either select one by hash of
unique, or poll them all. It's just not a good idea.

But, a simple solution is to have one worker that polls all of your
gearmand's for status and caches the response for a few seconds.

It would be kind of a cool and more scalable feature to have a variant of
the SUBMIT_JOB commands that would fail if there were no workers.

**Comment by tsmgeek** [comment]
We used this project to get a status list of all the current registered functions.
We only use it for monitoring so not sure of the performance if you were to poll it all the time.

One idea you could do is have your workers have a background interval/timer that keeps updating a flag in memcached/redis etc with timeout ie X seconds (longer than the time you expect your task to run), then while its there you know you have semi-alive workers else they have stopped.

**Comment by esabol** [comment]
The OP hasn’t responded. Since there is a way to do what they are asking, I’m going to close this issue.
