### ISSUE TITLE
Add a config option for a redis key prefix to allow multiple gearmand instances to use the same redis server

### ISSUE THREAD

**Issue by nickpeirson** [gearman/gearmand#60]
Currently it's not possible to have two (or more) separate gearmand instances use the same redis server as a queue backend as the keys may conflict, and restarting either gearmand instance will cause it to load all the jobs created on both instances.

A solution to this would be to add a config option to specify a key prefix, e.g. `--redis-key-prefix`, and prefix all of the entries in redis with this prefix.

**Comment by p-alik** [comment]
It is a general issue that concerns all other persistence plugins.

**Comment by nickpeirson** [comment]
Not all persistence plugins as, for example, this works in MySQL as you can [configure the table and schema](https://github.com/gearman/gearmand/blob/master/libgearman-server/plugins/queue/mysql/queue.cc#L107) to use. This would be comparable functionality for redis.

Perhaps it could be fixed in other plugins as well in a similar manner, but I'm really only familiar with MySQL and redis. I think it's less of an issue for the file based storages (tokyo cabinet, sqlite, etc) as you can easily just use separate files, but where you're running a server, e.g. MySQL or Redis, you probably want to reuse existing infrastructure.

**Comment by SpamapS** [comment]
Hi. I'd _highly_ recommend _not_ using the built in queue persistence plugins at all. They were added, IMO, in a misguided effort to expand gearmand's scope. If you need to have a non-scalable persistent queue, why not just _use Redis_ ?

If, however, you want to scale out the way gearmand was intended to be used, you should write workers that store foreground jobs somewhere safe (and since it's worker based, you can spread the load out), respond to the submitter that they have done so, and then re-submit them as foreground jobs backed by the database.

Anyway, this seems like a legitimate enhancement request for the redis plugin. As much as I think it's a misguided thing to use, we have it, and if you want to write code to add a --redis-key-prefix I won't say no to it.

**Comment by p-alik** [comment]
#204 solved the issue.
